name: PR Verification

on:
  pull_request:
    branches: [main, master]
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  verify:
    name: Verify PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/EnergiDataService.Client.sln

      - name: Build solution
        run: dotnet build src/EnergiDataService.Client.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/EnergiDataService.Client.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: success()
        with:
          files: "**/coverage.cobertura.xml"
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

